export const ENV = {
  HELIUS_API_KEY: "HELIUS_API_KEY",
  QUICKNODE_QPI_KEY: "QUICKNODE_QPI_KEY",
  IPINFO_API_KEY: "IPINFO_API_KEY",
  SOLSCAN_API_KEY: "SOLSCAN_API_KEY",
  PRIVATE_SERVER_API_KEY: "PRIVATE_SERVER_API_KEY",
  PRIVATE_SERVER_API_URL: "PRIVATE_SERVER_API_URL",
  TWITTER_BEARER_TOKEN: "TWITTER_BEARER_TOKEN",
} as const;
