export const ENV = {
  HELIUS_API_KEY: "HELIUS_API_KEY",
  QUICKNODE_QPI_KEY: "QUICKNODE_QPI_KEY",
  TWITTER_BEARER_TOKEN: "TWITTER_BEARER_TOKEN",
  IPINFO_API_KEY: "IPINFO_API_KEY",
  SOLSCAN_API_KEY: "SOLSCAN_API_KEY",
} as const;
